definitions:
  web.ApplicationKey:
    properties:
      appCert:
        type: string
      appPubKey:
        type: string
    type: object
  web.Attestation:
    properties:
      attestationVer:
        type: string
      deviceCert:
        type: string
      signature:
        type: string
      teePlatformVer:
        type: integer
    type: object
  web.DeleteKvRequest:
    properties:
      key:
        type: string
    type: object
  web.DeviceKey:
    properties:
      deviceCert:
        type: string
      devicePubKey:
        type: string
    type: object
  web.Enrollment:
    properties:
      deviceKey:
        type: string
      payload:
        type: string
      signature:
        type: string
    type: object
  web.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  web.QuotaResponse:
    properties:
      quota:
        type: integer
      used:
        type: integer
    type: object
  web.ReadKvResponse:
    properties:
      present:
        description: Present is the flag to indicate if the key exists
        type: boolean
      protected:
        description: Protected is the flag to indicate if the key is protected
        type: boolean
      protector:
        description: Protector is the protector of the key, if any
        type: string
      provisioned:
        description: Provisioned is the flag to indicate if the key is provisioned
        type: boolean
      provisioner:
        description: Provisioner is the provisioner of the key, if any
        type: string
      value:
        description: Value is the value of the key
        type: string
    type: object
  web.SignRequest:
    properties:
      data:
        description: Data is the data to be signed
        type: string
    type: object
  web.SignResponse:
    properties:
      pubKey:
        type: string
      signature:
        type: string
    type: object
  web.WriteKvRequest:
    properties:
      key:
        description: Key is the key to write
        type: string
      overwrite:
        description: Overwrite is the flag to overwrite the existing key, default
          is false
        type: boolean
      protected:
        description: Protected is the protector information, leave empty if not needed
        type: string
      provision:
        description: Provision is the provision information, leave empty if not needed
        type: string
      value:
        description: Value is the value to write
        type: string
    type: object
  web.WriteKvResponse:
    properties:
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/attestation/appkey:
    get:
      consumes:
      - application/json
      description: Get app derived key for current (simulated) tee version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ApplicationKey'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get app derived key for current (simulated) tee version
      tags:
      - attestation
  /api/v1/attestation/sign:
    post:
      consumes:
      - application/json
      description: Sign with app derived key for current (simulated) tee version
      parameters:
      - description: Data to be signed
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/web.SignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.SignResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Sign with app derived key for current (simulated) tee version
      tags:
      - attestation
  /api/v1/device/key:
    get:
      consumes:
      - application/json
      description: Get device key for current (simulated) tee version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.DeviceKey'
      summary: Get device key for current (simulated) tee version
      tags:
      - device
  /api/v1/device/sign:
    post:
      consumes:
      - application/json
      description: |-
        Get device enrollment key for current (simulated) tee version
        Please see also the DePhy evm sdk.
      parameters:
      - description: Data to be signed
        in: body
        name: signRequest
        required: true
        schema:
          $ref: '#/definitions/web.SignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Enrollment'
      summary: Get device enrollment key for current (simulated) tee version
      tags:
      - device
  /api/v1/device/version:
    get:
      consumes:
      - application/json
      description: Get version attestation for current (simulated) tee version
      parameters:
      - description: Remote requester's nonce and signature, serialized as hex(64b
          nonce || 64b pubKey || 65b signature), in which signature is the signature
          of nonce || pubKey, if signature not provided, omit signature
        in: query
        name: attestation
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Attestation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get version attestation for current (simulated) tee version
      tags:
      - device
  /api/v1/kv/delete:
    delete:
      consumes:
      - application/json
      description: Delete a key-value pair
      parameters:
      - description: Request to delete
        in: body
        name: DeleteRequest
        required: true
        schema:
          $ref: '#/definitions/web.DeleteKvRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WriteKvResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Delete a key-value pair
      tags:
      - kv
  /api/v1/kv/quota:
    get:
      description: Get the quota of the current application, return the number of
        keys that can be written
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.QuotaResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get the quota of the current application
      tags:
      - kv
  /api/v1/kv/read:
    get:
      consumes:
      - application/json
      description: Read a key-value pair, If the target key is protected, the protector
        must be provided.
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ReadKvResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Read a key-value pair
      tags:
      - kv
  /api/v1/kv/write:
    post:
      consumes:
      - application/json
      description: Write a key-value pair, If Provision is provided, the remote provision
        information will be added, and only the provisioner can write it, If Protected
        is provided, the target key will be protected, and only the protector can
        read it.
      parameters:
      - description: Key
        in: body
        name: keyInfo
        required: true
        schema:
          $ref: '#/definitions/web.WriteKvRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WriteKvResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Write a key-value pair
      tags:
      - kv
swagger: "2.0"
